-- 나만의 연애코치 — AI 답변 신고 표 (운영 Supabase SQL Editor 에 이 조각을 실행)
-- 새 DB 는 supabase/schema.sql 전체를 실행한다. 이 파일은 예전 스키마가 이미 적용된 운영 DB 에 신고 표만 더할 때 쓴다.
-- schema.sql 의 ai_report 부분과 같은 결과를 만든다. 여러 번 실행해도 안전하다.
--
-- 신고의 1년 파기는 purge_old_records() 와 따로 둔다 (purge_ai_report() + pg_cron 작업 mylovecoach-purge-report).
-- purge_old_records() 는 브랜치마다 본문이 달라(가입 판 = bonus_spent 파기, 1.0 판 = 유입 경로 비우기·usage_quota 정리)
-- 어느 판의 schema.sql 을 다시 실행하든 함수가 통째로 바뀌는데, 거기에 신고 줄을 붙여 두면 그때 아무 경고 없이 사라진다.
-- 그래서 이 파일은 purge_old_records() 를 건드리지 않고, schema.sql 과 어느 순서로 실행해도 된다.
-- (예전 판 조각을 이미 실행해 purge_old_records() 에도 신고 줄이 있다면 같은 행을 두 번 지우려는 것뿐이라 그대로 둬도 된다)

-- ── AI 답변 신고 (앱 안에서 불쾌·부적절한 AI 답변을 신고 — 구글 플레이 생성형 AI 정책) ─
-- 이용 기록 동의와 관계없이 이용자가 「신고하기」를 누른 것만 들어온다 (api/report.ts).
-- 누가 보냈는지 남기지 않도록 기기 ID·IP 칸은 두지 않는다. 1년 지나면 파기
create table if not exists ai_report (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  mode        text not null,                 -- coach · report · practice · mind
  reason      text not null,                 -- offensive · sexual · hate · dangerous · inaccurate · other
  note        text,                          -- 이용자가 적은 메모 (300자까지)
  content     text,                          -- 신고한 AI 답변 (4000자까지, 마이 탭에서 메모만으로 신고하면 비어 있음)
  model       text,                          -- 답변이 나온 곳 (예: google/relay)
  platform    text,                          -- ios | android | web
  app_version text,
  status      text not null default 'new'    -- 검토 표시 (new → done)
);
create index if not exists ai_report_created_idx on ai_report (created_at desc);

-- 공개 키(anon)로는 읽기·쓰기 불가 — 서버(service_role)만
alter table ai_report enable row level security;

-- ── 하루 저장 상한 (공개된 앱 주소로 무료 DB 를 채우지 못하게) ─────────────
-- 앱 토큰은 공개 번들에 들어 있어 누구나 /api/report 를 부를 수 있고, 서버의 IP 빈도 제한은 인스턴스마다 따로 센다.
-- 그래서 저장하는 쪽에서 한국 날짜로 하루 300건, 또는 데이터베이스 전체가 400MB(무료 플랜 500MB)를 넘으면 저장을 거절한다.
-- 거절은 PostgREST 가 429·503 으로 돌려주고(PTxyz → HTTP xyz), 서버(api/report.ts)도 429·503 으로 답해 앱 시트는 닫지 않고 안내를 보여 준다.
-- 상한을 바꾸려면 아래 300 을 고쳐 이 파일을 다시 실행한다 (schema.sql 의 같은 함수도 같이 고칠 것)
create or replace function ai_report_quota()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if pg_database_size(current_database()) > 400::bigint * 1024 * 1024 then
    raise exception using errcode = 'PT503', message = 'ai_report: 데이터베이스가 400MB 를 넘어 신고를 저장하지 않음';
  end if;
  if (select count(*) from ai_report
       where created_at >= date_trunc('day', now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul') >= 300 then
    raise exception using errcode = 'PT429', message = 'ai_report: 오늘 신고 저장 상한(300건)을 넘음';
  end if;
  return new;
end $$;

drop trigger if exists ai_report_quota on ai_report;
create trigger ai_report_quota before insert on ai_report
  for each row execute function ai_report_quota();

-- ── 1년 파기 (purge_old_records 와 따로, 매일 03:35 KST) ─────────────────
create or replace function purge_ai_report()
returns void
language sql
security definer
set search_path = public
as $$
  delete from ai_report where created_at < now() - interval '1 year';
$$;

comment on function purge_ai_report is 'AI 답변 신고 1년 파기 (pg_cron mylovecoach-purge-report 매일 03:35 KST — purge_old_records 와 따로 둔다)';

-- 서버(service_role)와 예약 작업만 부를 수 있게
do $$
begin
  revoke execute on function purge_ai_report() from public;
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke execute on function purge_ai_report() from anon, authenticated;
  end if;
end $$;

-- 매일 03:35(한국 시간) = 18:35 UTC. pg_cron 을 쓸 수 없는 곳(로컬 시험 등)에서는 건너뛴다
do $$
begin
  begin
    create extension if not exists pg_cron;
  exception when others then
    raise notice 'pg_cron 을 켤 수 없어 신고 1년 파기 예약을 건너뜁니다: %', sqlerrm;
    return;
  end;
  perform cron.unschedule(jobid) from cron.job where jobname = 'mylovecoach-purge-report';
  perform cron.schedule('mylovecoach-purge-report', '35 18 * * *', 'select public.purge_ai_report()');
end $$;

-- 확인 (결과: ai_report RLS true · 상한 트리거 1개 · 예약 작업 mylovecoach-purge(이용 기록)와 mylovecoach-purge-report(신고) 둘 다 active)
select c.relname, c.relrowsecurity from pg_class c where c.relname = 'ai_report';
select tgname from pg_trigger where tgrelid = 'public.ai_report'::regclass and not tgisinternal;
select jobname, schedule, command, active from cron.job where jobname like 'mylovecoach-purge%' order by jobname;
