-- 나만의 연애코치 — AI 답변 신고 표 (운영 Supabase SQL Editor 에 이 조각만 실행)
-- 새 DB 는 supabase/schema.sql 전체를 실행한다. 이 파일은 예전 스키마가 이미 적용된 운영 DB 에 신고 표만 더할 때 쓴다.
-- schema.sql 의 ai_report 부분과 같은 결과를 만든다. 여러 번 실행해도 안전하다.
--
-- 주의: 운영 purge_old_records() 는 어느 브랜치의 schema.sql 이 마지막으로 적용됐는지에 따라 본문이 다르다
--       (가입 브랜치 dded16c 판 = bonus_spent 파기 줄, 1.0 134bf0f 판 = 유입 경로 비우기·usage_quota 정리 줄 등).
--       함수를 통째로 다시 만들면 다른 판의 줄이 사라지므로, 아래는 「지금 운영 함수 본문 끝에 신고 파기 한 줄만 붙인다」.
--       이미 ai_report 줄이 있으면 아무것도 하지 않는다.

-- ── AI 답변 신고 (앱 안에서 불쾌·부적절한 AI 답변을 신고 — 구글 플레이 생성형 AI 정책) ─
-- 이용 기록 동의와 관계없이 이용자가 「신고하기」를 누른 것만 들어온다 (api/report.ts).
-- 누가 보냈는지 남기지 않도록 기기 ID·IP 칸은 두지 않는다. 1년 지나면 파기
create table if not exists ai_report (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  mode        text not null,                 -- coach · report · practice · mind
  reason      text not null,                 -- offensive · sexual · hate · dangerous · inaccurate · other
  note        text,                          -- 이용자가 적은 메모 (300자까지)
  content     text,                          -- 신고한 AI 답변 (4000자까지, 마이 탭에서 메모만으로 신고하면 비어 있음)
  model       text,                          -- 답변이 나온 곳 (예: google/relay)
  platform    text,                          -- ios | android | web
  app_version text,
  status      text not null default 'new'    -- 검토 표시 (new → done)
);
create index if not exists ai_report_created_idx on ai_report (created_at desc);

-- 공개 키(anon)로는 읽기·쓰기 불가 — 서버(service_role)만
alter table ai_report enable row level security;

-- ── 1년 파기: 지금 운영 함수 본문 끝에 한 줄만 붙인다 ─────────────────────
do $$
declare
  body text;
begin
  select p.prosrc into body
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'purge_old_records' and p.pronargs = 0;
  if body is null then
    raise exception 'public.purge_old_records() 가 없습니다 — supabase/schema.sql 전체를 먼저 실행하세요';
  end if;
  if position('ai_report' in body) > 0 then
    raise notice 'purge_old_records() 에 이미 ai_report 파기가 있어 그대로 둡니다';
    return;
  end if;
  execute format(
    'create or replace function public.purge_old_records() returns void language sql security definer set search_path = public as %L',
    rtrim(body, E' \t\r\n') || E'\n  delete from ai_report       where created_at   < now() - interval ''1 year'';\n'
  );
  execute format(
    'comment on function public.purge_old_records() is %L',
    coalesce(obj_description('public.purge_old_records()'::regprocedure, 'pg_proc'), '1년 지난 이용 기록 파기') || ' · AI 답변 신고 1년 파기'
  );
end $$;

-- create or replace 는 기존 권한을 그대로 두지만, 서버만 부를 수 있게 한 번 더 막아 둔다
do $$
begin
  revoke execute on function purge_old_records() from public;
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke execute on function purge_old_records() from anon, authenticated;
  end if;
end $$;

-- 확인 (결과: ai_report 표 1개 · RLS true · 함수에 ai_report 파기 줄이 1개, 원래 있던 줄은 그대로)
select c.relname, c.relrowsecurity from pg_class c where c.relname = 'ai_report';
select (length(prosrc) - length(replace(prosrc, 'delete from ai_report', ''))) / length('delete from ai_report') as ai_report_lines, prosrc
from pg_proc where proname = 'purge_old_records';
